Fix taco-test compilation
taco/test/tests-tensor_types.cpp: In instantiation of 'void gtest_case_VectorTensorTest_::types<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = unsigned char]':
taco/test/tests-tensor_types.cpp:42:1:   required from here
taco/test/tests-tensor_types.cpp:48:30: error: narrowing conversion of '1.0e+0' from 'double' to 'unsigned char' [-Wnarrowing]
   48 |   map<vector<int>,TypeParam> vals = {{{0}, 1.0}, {{2}, 2.0}};
      |